include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true
    always_specify_types: false
    avoid_classes_with_only_static_members: true
    avoid_empty_else: true
    camel_case_types: true
    prefer_mixin: true