name: flutter_advanced
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  intl: ^0.19.0
  battery_plus: ^5.0.2
  camera: ^0.10.5+9
  flutter_bloc: ^8.1.3
  flutter_colorpicker: ^1.0.3
  feedback: ^3.0.0
  flutter_screenutil: ^5.9.0
  flutter_animate: ^4.4.0
  alarm: ^3.0.5
  flame: ^1.14.0
  ocr_scan_text: ^1.3.1
  geolocator: ^10.1.0
  just_audio: ^0.9.36
  home_widget: ^0.4.1
  model_viewer_plus: ^1.7.0
  flex_color_scheme: ^7.3.1
  getwidget: ^4.0.0
  any_link_preview: ^3.0.1
  url_launcher: ^6.2.5

dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/sounds/
