name: flutter_advanced
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  intl: ^0.20.2
  battery_plus: ^6.2.1
  camera: ^0.11.1
  flutter_bloc: ^9.1.1
  flutter_colorpicker: ^1.1.0
  feedback: ^3.1.0
  flutter_screenutil: ^5.9.3
  flutter_animate: ^4.5.2
  alarm: ^5.1.3
  flame: ^1.28.1
#  ocr_scan_text: ^1.3.1
  geolocator: ^14.0.0
  just_audio: ^0.10.3
  home_widget: ^0.7.0+1
  model_viewer_plus: ^1.9.3
  flex_color_scheme: ^8.2.0
  getwidget: ^6.0.0
  any_link_preview: ^3.0.3
  url_launcher: ^6.3.1
  webview_flutter: ^4.12.0
  mask_text_input_formatter: ^2.9.0
  timeago: ^3.7.1
  flutter_widget_from_html: ^0.16.0
  firebase_core: ^3.13.0
  firebase_remote_config: ^5.4.3
  firebase_analytics: ^11.4.5
  firebase_ui_auth: ^1.16.1
  google_sign_in: ^6.3.0
  firebase_ui_oauth_google: ^1.4.1
  auto_exporter_annotation: ^1.0.2
  win32: ^5.13.0
  skeletonizer: ^1.4.3

dependency_overrides:
  camera: ^0.10.2+1
#  web: ^0.5.1
  intl: ^0.19.0
  file_picker: ^10.1.9
  just_audio: ^0.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  auto_exporter: ^3.5.0
  build_runner: ^2.4.15
  build_test: ^2.2.3


flutter:

  uses-material-design: true

  assets:
    - assets/sounds/
    - assets/images/

  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf

