name: flutter_advanced
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  intl: ^0.18.1
  battery_plus: ^5.0.2
  camera: ^0.10.5+7
  flutter_bloc: ^8.1.3
  flutter_colorpicker: ^1.0.3
  feedback: ^3.0.0
  flutter_screenutil: ^5.9.0
  showcaseview: ^2.0.3
  flutter_animate: ^4.3.0
  alarm: ^2.1.1
  flame: ^1.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/sounds/
