name: flutter_advanced
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  intl: ^0.19.0
  battery_plus: ^6.0.2
  camera: ^0.11.0+2
  flutter_bloc: ^8.1.6
  flutter_colorpicker: ^1.1.0
  feedback: ^3.1.0
  flutter_screenutil: ^5.9.3
  flutter_animate: ^4.5.0
  alarm: ^3.1.5
  flame: ^1.18.0
  ocr_scan_text: ^1.3.1
  geolocator: ^13.0.1
  just_audio: ^0.9.39
  home_widget: ^0.6.0
  model_viewer_plus: ^1.8.0
  flex_color_scheme: ^7.3.1
  getwidget: ^4.0.0
  any_link_preview: ^3.0.2
  url_launcher: ^6.3.0
  webview_flutter: ^4.8.0
  mask_text_input_formatter: ^2.9.0
  timeago: ^3.7.0
  flutter_widget_from_html: ^0.15.1
  firebase_core: ^3.3.0
  firebase_remote_config: ^5.0.4
  firebase_analytics: ^11.2.1
  firebase_ui_auth: ^1.15.0
  google_sign_in: ^6.2.1
  firebase_ui_oauth_google: ^1.3.3
  auto_exporter_annotation: ^1.0.1

dependency_overrides:
  camera: ^0.10.2+1
  web: ^0.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  auto_exporter: ^3.4.1
  build_runner: ^2.4.12
  build_test: ^2.2.2

flutter:

  uses-material-design: true

  assets:
    - assets/sounds/

  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf

