name: flutter_advanced
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  intl: ^0.19.0
  battery_plus: ^6.0.1
  camera: ^0.10.5+9
  flutter_bloc: ^8.1.5
  flutter_colorpicker: ^1.0.3
  feedback: ^3.0.1
  flutter_screenutil: ^5.9.0
  flutter_animate: ^4.5.0
  alarm: ^3.1.0
  flame: ^1.17.0
  ocr_scan_text: ^1.3.1
  geolocator: ^11.0.0
  just_audio: ^0.9.37
  home_widget: ^0.5.0
  model_viewer_plus: ^1.7.2
  flex_color_scheme: ^7.3.1
  getwidget: ^4.0.0
  any_link_preview: ^3.0.2
  url_launcher: ^6.2.6
  webview_flutter: ^4.7.0
  mask_text_input_formatter: ^2.9.0
  timeago: ^3.6.1
  flutter_widget_from_html: ^0.14.11
  firebase_core: ^2.30.1
  firebase_remote_config: ^4.4.4
  firebase_analytics: ^10.10.4
  firebase_ui_auth: ^1.14.0
  google_sign_in: ^6.2.1
  firebase_ui_oauth_google: ^1.3.2
  auto_exporter_annotation: ^1.0.1

dependency_overrides:
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.2
  auto_exporter: ^3.1.1
  build_runner: ^2.4.6
  build_test: ^2.2.0

flutter:

  uses-material-design: true

  assets:
    - assets/sounds/

  fonts:
    - family: SocialIcons
      fonts:
        - asset: packages/firebase_ui_auth/fonts/SocialIcons.ttf

