// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJNv00rbmdb2rDkrOo_Xh4MQ060VLDLeM',
    appId: '1:729770279490:web:114b32b0aec147316ee3db',
    messagingSenderId: '729770279490',
    projectId: 'flutter-advanced-ef296',
    authDomain: 'flutter-advanced-ef296.firebaseapp.com',
    storageBucket: 'flutter-advanced-ef296.appspot.com',
    measurementId: 'G-54WXXPGTTP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv0ML_fACFIxrUZkA1H2ahNi8FWRsmuec',
    appId: '1:729770279490:android:07dbc07b2a7eb5e66ee3db',
    messagingSenderId: '729770279490',
    projectId: 'flutter-advanced-ef296',
    storageBucket: 'flutter-advanced-ef296.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJXym30EAUrHZ3-LRzJPLJI_vMeNFezJs',
    appId: '1:729770279490:ios:482b35e075787b9d6ee3db',
    messagingSenderId: '729770279490',
    projectId: 'flutter-advanced-ef296',
    storageBucket: 'flutter-advanced-ef296.appspot.com',
    androidClientId: '729770279490-qaiv5mbpljsunec4o72c2ktdafc1mir7.apps.googleusercontent.com',
    iosClientId: '729770279490-ml6eevkljlj8gk5mi98t67pmca2hdubp.apps.googleusercontent.com',
    iosBundleId: 'com.assaf.flutterAdvanced',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJXym30EAUrHZ3-LRzJPLJI_vMeNFezJs',
    appId: '1:729770279490:ios:482b35e075787b9d6ee3db',
    messagingSenderId: '729770279490',
    projectId: 'flutter-advanced-ef296',
    storageBucket: 'flutter-advanced-ef296.appspot.com',
    androidClientId: '729770279490-qaiv5mbpljsunec4o72c2ktdafc1mir7.apps.googleusercontent.com',
    iosClientId: '729770279490-ml6eevkljlj8gk5mi98t67pmca2hdubp.apps.googleusercontent.com',
    iosBundleId: 'com.assaf.flutterAdvanced',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJNv00rbmdb2rDkrOo_Xh4MQ060VLDLeM',
    appId: '1:729770279490:web:d55b19ff8286a5fa6ee3db',
    messagingSenderId: '729770279490',
    projectId: 'flutter-advanced-ef296',
    authDomain: 'flutter-advanced-ef296.firebaseapp.com',
    storageBucket: 'flutter-advanced-ef296.appspot.com',
    measurementId: 'G-YV38C8BWE3',
  );

}